install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")

install.packages('leaflet')
install.packages("shiny")
install.packages("dplyr")
install.packages("readr")
install.packages("RColorBrewer")
install.packages("scales")
install.packages("lattice")
install.packages("shinyjs")
install.packages("leaflet.extras")
install.packages("sp")
install.packages("rvest")
install.packages("raster")
install.packages("DT")
install.packages("htmlwidgets")
install.packages("ggplot2")
install.packages("rjson")
install.packages("RCurl")
install.packages("ggthemes")
install.packages("dplyr")

# install.packages("devtools")
# devtools::install_github("khufkens/MODISTools", build_vignettes = FALSE)