install.packages('RPostgreSQL')
install.packages('devtools')
install.packages('leaflet')
install.packages('shiny')
install.packages('dplyr')
install.packages('readr')
install.packages('RColorBrewer')
install.packages('scales')
install.packages('lattice')
install.packages('geojsonio')
install.packages('shinyjs')
install.packages('leaflet.extras')
install.packages('sp')
install.packages('rvest')
install.packages('raster')
install.packages('magick')
install.packages('rgdal')
install.packages('DT')
install.packages('htmlwidgets')

#   Fake example
# require(devtools)
# install_version("shiny", version='1.2.3.4')