---
title: "APIS_insitu_paper_figs"
author: "K Duffy"
date: "3/3/2020"
output:
  pdf_document: default
  html_document: default
---
```{r}
library(dplyr)
library(lubridate)
```

```{r}
df <- read.table('/Users/kdw223/Research/PostDoc/phenoSynth/Notebooks/greenwave_dacqre/npn_data/Jornada_StatusandIntensity_leaves.csv', header = TRUE, sep = ",", stringsAsFactors = FALSE)
df=df%>%
  filter(df$Intensity_Value!=-9999)
df=df%>%
  filter(df$Phenophase_Description==c('Leaves', 'Leaves (grasses)'))
#df$Observation_Date=as.Date(df$Observation_Date, format="%m/%d/%Y")
df$Observation_Date=mdy(df$Observation_Date)
xscale=data.frame(unique(df$Intensity_Value))
```
```{r}

npn_SH=df%>%
  filter(Functional.Type=='shrub')%>%
  arrange(Observation_Date) %>%
  rename(date=Observation_Date) %>% rowwise() %>% dplyr::mutate(percent_int_value = strsplit(Intensity_Value, '-')[[1]][2]) %>%
  dplyr::mutate(percent_int_value = substr(percent_int_value,1,nchar(percent_int_value)-1))%>%
  dplyr::mutate(percent_int_value = as.integer(percent_int_value)) %>% ungroup() %>%
  dplyr::group_by(date) %>% dplyr::mutate(mean_status_int = mean(percent_int_value)) %>% 
  dplyr::select(mean_status_int, date, Functional.Type) %>% dplyr::distinct()
head(npn_SH)
```

```{r}
npn_GR=df%>%
  filter(Functional.Type=='grass')%>%
  arrange(Observation_Date) %>%
  rename(date=Observation_Date) %>% rowwise() %>% dplyr::mutate(percent_int_value = strsplit(Intensity_Value, '-')[[1]][2]) %>%
  dplyr::mutate(percent_int_value = substr(percent_int_value,1,nchar(percent_int_value)-1)) %>%
  dplyr::mutate(percent_int_value = as.integer(percent_int_value)) %>% ungroup() %>%
  dplyr::group_by(date) %>% dplyr::mutate(mean_status_int = mean(percent_int_value)) %>% 
  dplyr::select(mean_status_int, date, Functional.Type) %>% dplyr::distinct()
  
head(npn_GR)
```

```{r}

library(plotly)
p2 = plot_ly(
  
)%>%
   add_trace(
      x=~as.factor(npn_SH$date),
     y=~as.factor(npn_SH$mean_status_int),
     type = "bar",
     #mode='lines', 
    opacity = 1,
     name='USA-NPN Shrubs',
     yaxis='y',
     marker = list(color="royalblue", width=4)
  )%>%
add_trace(
    data = npn_GR,
    x = ~ as.factor(npn_GR$date),
    y = ~ as.factor(npn_GR$mean_status_int),
    showlegend = TRUE,
    type = 'bar',
    #mode='lines',
    opacity = 1,
    name='USA-NPN Grass', 
    yaxis='y',
    #text=unique(df$Intensity_Value),
    marker=list(color="goldenrod", width=4)
   ) 

```

```{r}
p2 <- p2 %>%
  layout(
    #title = "Time Series of ibp & JORN.00042",
   # xaxis = list(title='Date'),
    xaxis = list(
        type = 'date',
        tickformat = " %B<br>%Y", 
        title='Date', 
        zeroline=FALSE),
        
        yaxis = list(
          title = 'USA-NPN <br> Status Intensity',
          typeformat='%', 
          nticks=6,
          tick0=0,
          dtick=25,
          ticktext=xscale, 
          barmode = 'group', 
          zeroline=FALSE
          # tick0=5,
          # dtick=25, 
          # tick
          #range=c(0,100))
        # yaxis = list(
        # range=c(0,100))
  ))
#orca(p2, 'npn_plot_v3.png', height = 8 * 96, width = 11 * 96)
p2


```

```{r}
p2 <- p2 %>%
  layout(
    #title = "Time Series of ibp & JORN.00042",
   # xaxis = list(title='Date'),
    xaxis = list(
        type = 'date',
        tickformat = " %B<br>%Y", 
        title='Date'),
        
        yaxis = list(
          title = 'USA-NPN Status Intensity',
          typeformat='%', 
          nticks=6,
          tick0=0,
          dtick=25,
          ticktext=xscale
          # tick0=5,
          # dtick=25, 
          # tick
          #range=c(0,100))
        # yaxis = list(
        # range=c(0,100))
  ))

p2

# a <- list(
#   autotick = FALSE,
#   ticks = "outside",
#   tick0 = 0,
#   dtick = 25,
#   ticklen = 5,
#   tickwidth = 2
# )
# s <- seq(1, 4, by = 0.25)
# fig <- plot_ly(x = ~s, y = ~s)
# fig <- fig %>% layout(xaxis = a, yaxis = a)
# 
# fig
```

```{r}
# p3=subplot(p2, p, nrows=2, shareX = TRUE, titleY = TRUE)
# p3
# orca(p3, 'npn-phenocam_plot_v2.png', height = 8 * 96, width = 11 * 96)
# p3=subplot(p2, p,fig,fig_landsat,fig_clim, fig_clim2,  nrows=6, shareX=TRUE, titleY = TRUE) #fig_clim,
# p3
#orca(p3, 'panels1-3v2.png')
```

```{r}
# p3=subplot(p2, fig_clim,  nrows=2) #fig_clim,
# p3
```