---
title: "pull jornada phenocam data"
author: "K Duffy"
date: "2/20/2020"
output: html_document
---


```{r, silent=TRUE}
library(phenocamapi)
library(phenocamr)
library(dplyr)
```

Start by pulling in a list of PhenoCam sites:



```{r}
phenos=list_rois()
#and let's check the column names:
colnames(phenos)

full_list=get_rois()

```

Filter for sites used in this paper and remove non-vegetated ROIs:
```{r}
site_names=c('ibp', 'jernort', 'NEON.D14.JORN.DP1.00042')
jer=phenos%>%
filter(is.element(phenos$site,site_names))
head(jer)

jer_full_list= full_list%>%
  filter(is.element(full_list$site,site_names))%>%
  filter(!roitype=='NV') #remove 'No Vegetation' NV ROIs 
head(jer_full_list)
```

```{r}
n=nrow(jer)
for(i in seq(1, n, by = 1)){
  phenocamr::download_phenocam(
  frequency = 3,
  veg_type = jer$primary_veg_type[i],
  roi_id = 1000,
  site = jer$site[i],
  phenophase = FALSE,
  out_dir = "YOUR/PATH/HERE"
  )
}
```


Alternately, if you only want to pull the phenocam data into your R session:

```{r}
ibp_SH=get_pheno_ts('ibp', 'SH', 1000, '3day')
#where you can eighter directly reference the phenos df, different PFT's or ROI 3's, or timesteps.
```
Hope this helps!
K