---
title: "Viz Shrubs"
author: "K Duffy"
date: "2/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
SH_files=list.files('/Users/kdw223/Research/PostDoc/phenoSynth/Notebooks/greenwave_dacqre/phenocam_data/SH')
n_sh=length(SH_files)
```

```{r}
jer_SH=data.frame(date=seq(as.Date('2014-01-01'),to=as.Date('2019-12-30'),by='1 day'))
jer_SH=jer_SH%>%
  dplyr::mutate(
    date=as.factor(date)
    )
```
```{r}
setwd('/Users/kdw223/Research/PostDoc/phenoSynth/Notebooks/greenwave_dacqre/phenocam_data/SH')
for(i in seq(1, n_sh, by = 1)){
  print(SH_files[i])
          df <- read.table(SH_files[i], header = TRUE, sep = ",")
          df=df%>%
            dplyr::select(date, year, doy, gcc_90, smooth_gcc_90)

            jer_SH=jer_SH%>%
              dplyr::left_join(df, jer_SH, by="date")
}
#
```

```{r}
# jer_smoothed=jer_GR%>%
#   select(date, starts_with('smooth'))
jer_SH=jer_SH%>%
  select(date,starts_with('gcc'))
colnames(jer_SH)=c('date', 'ibp', 'jerbajada', 'jernert1000', 'jernort2000', 'jernovel', 'jerwern', 'jersand', 'jershrubland')

meltedSH=melt(jer_SH)
```

```{r}
p = plot_ly(
    data = meltedGR,
    x = ~ date,
    y = ~ value,
    showlegend = TRUE,
    type = 'scatter',
    mode = 'markers', 
     opacity = .8,
    name='Jornada PhenoCam Grass',
    marker=list(color="goldenrod", size=3)
  ) %>%
  add_trace(
     x=~meltedSH$date,
    y=~meltedSH$value,
    mode = "markers",
    type = "scatter",
     opacity = .5,
    name='Jornada PhenoCam Shrubs',
    marker = list(color="royalblue", size=3)
  )
p
```