---
title: "phenoAPI"
author: "K. Duffy"
date: "8/27/2018"
output: html_document
---

```{r setup, include=FALSE}
library(jsonlite)

rois=fromJSON('https://phenocam.sr.unh.edu/api/roilists/?format=json&limit=753')
roi_files=rois$results

```

```{r}
table_url = 'https://phenocam.sr.unh.edu/webcam/network/siteinfo/?format=csv'
df <- read.csv(url(table_url))
colnames(df)
cams_ = df
```

```{r}
test_site=cams_[9,]
site_data=test_site
veg_idx=is.element(roi_files$site, test_site$site)
veg_match=roi_files[veg_idx,]
```

```{r}
seq_idx=roi_files$sequence_number>1000
roi_files=roi_files[!seq_idx,]
```

```{r}
pft_key = c(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,254,255)
pft_abbreviated = c('Water','EN','EB','DN','DB','MF','SH','SH','SV','SV','GR','WL','AG','UB','MX','TN','UN','NAN','NAN')
pft_expanded = c('Water', 'Evergreen Needleleaf Forest', 'Evergreen Broadleaf Forest', 'Deciduous Needleleaf Forest', 'Deciduous Broadleaf Forest', 'Mixed Forest',
                 'Shrubland', 'Shrubland', 'Savanna', 'Savanna','Grassland', 'Wetland', 'Agriculture', 'Urban', 'Mixed Forest', 'Tundra', 'Understory', 'Unclassified', 'Unclassified' )
pft_df = data.frame(pft_key,pft_abbreviated,pft_expanded)
```

```{r}
veg.idx   = is.element(pft_df$pft_abbreviated, veg_match$roitype[1] )
    prim_veg  = pft_df$pft_expanded[veg.idx]
    prim_veg  = as.character(prim_veg[1])
    veg_num1=pft_df$pft_key[veg.idx]
```
    
    ```{r}
    
    veg.idx   = is.element(pft_df$pft_abbreviated, veg_match$roitype[2])
    secon_veg = pft_df$pft_expanded[veg.idx]
    secon_veg = as.character(secon_veg[1])
    veg_types = rbind(prim_veg, secon_veg)
    veg_num2=pft_df$pft_key[veg.idx]
    veg_nums=rbind(veg_num1, veg_num2)
    veg_types=cbind(veg_types, veg_nums)
    veg_types=data.frame(veg_types)
    dplyr::rename(veg_types, PFT.txt=X1, PFT.num=X2)
```

```{r}
  # Button switches to Analyzer Mode
  observeEvent(input$analyzerMode,{
    panel$mode = 'analyzer'
    site       = input$site
    site_data  = get_site_info(site)

    print ('Switching to Analyze Mode')
    zoom_to_site(site, TRUE)
    test_site=site_data
    veg_idx=is.element(roi_files$site, test_site$site)
    veg_match=roi_files[veg_idx,]
    output$analyzerTitle = renderText({paste0('Site:: ', site)})
    switch_to_analyzer_panel()
    
    veg.idx   = is.element(pft_df$pft_abbreviated, veg_match$roitype[1] )
    prim_veg  = pft_df$pft_expanded[veg.idx]
    prim_veg  = as.character(prim_veg[1])
    veg_num1=pft_df$pft_key[veg.idx]
    veg.idx   = is.element(pft_df$pft_abbreviated, veg_match$roitype[2])
    secon_veg = pft_df$pft_expanded[veg.idx]
    secon_veg = as.character(secon_veg[1])
    veg_types = rbind(prim_veg, secon_veg)
    veg_num2=pft_df$pft_key[veg.idx]
    veg_nums=rbind(veg_num1, veg_num2)
    veg_types=cbind(veg_types, veg_nums)
    veg_types=data.frame(veg_types)
    dplyr::rename(veg_types, PFT.txt=X1, PFT.num=X2)
    print(veg_types)
    
    primary_key   = veg_types[1,]
    secondary_key = veg_types[2,]
    
    c           = c('#79c400', '#ffee00')
    r      = crop_MODIS_2016_raster(site_data$lat, site_data$lon, reclassify=FALSE)
    data$r = r
    
    prim_b  = FALSE
    secon_b = FALSE
    if (site_data$primary_veg_type[1] == ''){print ('no primary vegetation type found')
    }else{
      # print (prim_veg)
      prim_b    = TRUE
      prim_veg  = paste0('Primary: ', prim_veg)
      #veg_types = append(veg_types, as.character(prim_veg))
      rc        = crop_MODIS_2016_raster(site_data$lat, site_data$lon, reclassify=TRUE,
                                  prim = as.numeric(veg_types[1, 2]))
    }
    if (site_data$secondary_veg_type[1] == ''){print ('no secondary vegetation type found')
    }else{
      # print (secon_veg)
      secon_b   = TRUE
      secon_veg = paste0('Secondary: ', secon_veg)
      veg_types = append(veg_types, as.character(secon_veg))
      rc        = crop_MODIS_2016_raster(site_data$lat, site_data$lon, reclassify=TRUE, 
                                  prim = as.numeric(veg_types[1, 2]), sec = as.numeric(veg_types[2, 2]))
    }
    if (prim_b|secon_b == TRUE){
      leafletProxy('map') %>% 
        addRasterImage(data$r, opacity = .65, project=TRUE, group='MODIS Land Cover 2016', colors = data$c2) %>%
        addRasterImage(rc, opacity = .55, project=TRUE, group= 'MODIS Reclassified 2016', colors=c) %>%
        addLayersControl(baseGroups = c("World Imagery", "Open Topo Map"),
                         overlayGroups = c('MODIS Land Cover 2016', 'MODIS Reclassified 2016'),
                         position = c("topleft"),
                         options = layersControlOptions(collapsed = FALSE))
    }

    if (is.null(veg_types)){
      updateSelectInput(session, 'pftSelection', choices = 'No ROI Vegetation Available')
    }else{
      updateSelectInput(session, 'pftSelection', choices = veg_types[,1])
    }
  })
```

```{r}
  # Creates boundary box for clipping rasters using lat/lon from phenocam site
  crop_MODIS_2016_raster = function(lat_, lon_, reclassify=FALSE, primary=NULL, secondary=NULL){
    # us_pth = './www/uslandcover_modis_sinu.tif'
    us_pth = './www/uslandcover_modis.tif'
    
    us_r   = raster(us_pth)
    resolution = res(us_r)[1]
    print (us_r)
    print (resolution)
    
    height = 5 * resolution
    width  = 5 * resolution
    e      = as(extent(lon_-width, lon_ + width, lat_ - height, lat_ + height), 'SpatialPolygons')

    crs(e) <- "+proj=longlat +datum=WGS84 +no_defs"
    r      = crop(us_r, e)
    
    if (reclassify == FALSE){
      return (r)
      
    }else if (reclassify == TRUE){
      
      water = 17*2
      
      m = c(1,NA,
            2,NA,
            3,NA,
            4,NA,
            5,NA,
            6,NA,
            7,NA,
            8,NA,
            9,NA,
            10,NA,
            11,NA,
            12,NA,
            13,NA,
            14,NA,
            15,NA,
            16,NA,
            17,NA)
      
      if(!is.null(primary)){
        prim    = primary*2
        m[prim] = 1
        }
      if(!is.null(secondary)){
        sec    = secondary*2
        m[sec] = 2
        }

      # m[water] = 3
      
      rclmat = matrix(m, ncol=2, byrow=TRUE)
      rc     = reclassify(r, rclmat)
      
      return (rc)
    }
  }
```
