---
title: "RSsmoothing"
author: "K Duffy"
date: "5/14/2019"
output: html_document
---

```{r setup, include=FALSE}
readRDS('testLOESSdata.rds')

```

```{r}
head(testLOESSdata)
```

```{r}
mNDVI=testLOESSdata %>%
  group_by(date) %>%
  summarise(meanNDVI = mean(ndvi_raw))%>%
```
```{r}

mEVI=testLOESSdata2 %>%
  filter(!is.na(testLOESSdata2$evi_raw)) %>%
  group_by(date) %>%
  summarise(meanEVI = mean(evi_raw))
```
#regular smooth
```{r}
ndvi_p = plot_ly() %>%
  add_trace(
    x=mNDVI$date,
    y=mNDVI$meanNDVI
  )%>%
  add_lines(
    x=mNDVI$date, 
    y=smooth(mNDVI$meanNDVI)
  )
ndvi_p
```
#use this one
```{r}
ndvi_p = plot_ly() %>%
  add_trace(
    x=mNDVI$date,
    y=mNDVI$meanNDVI
  )%>%
  add_lines(
    x=mNDVI$date, 
    y=~fitted(smooth.spline(mNDVI$meanNDVI~as.numeric(mNDVI$date)), data=mNDVI)
  )
ndvi_p

```

```{r}
evi_p = plot_ly() %>%
  add_trace(
    x=mEVI$date,
    y=mEVI$meanEVI
  )%>%
  add_lines(
    x=mEVI$date, 
    y=~fitted(smooth.spline(mEVI$meanEVI~as.numeric(mEVI$date)), data=mEVI)
  )
evi_p
```