---
title: "phenocam_analysis"
author: "K. Enns"
date: "1/30/2020"
output: html_document
---

### RUN Global.R

Read in the NLCD and MODIS LC dataframe for phenocam network data
```{r}
pc_analysis_df = read.csv('phenocam_analysis_2020_01_30_141833.csv', stringsAsFactors = FALSE) %>% 
  mutate(pft_abbreviated = replace(pft_abbreviated, Var1 == 17, 'WA')) %>%
  mutate(pft_expanded = replace(pft_expanded, Var1 == 17, 'Water'))
pc_analysis_df
```


Get variables we will use later
```{r}
# Number of phenocam sites
all_sites = unique(pc_analysis_df$site)
num_sites = length(all_sites)
num_sites

# All the different pixel ids we will use
ids = unique(pc_analysis_df$id)
ids
```

Get all of the NLCD data in a format we can use to plot
```{r}
nlcd_df_1 = pc_analysis_df %>% subset(id == '1by1') %>%
  subset(type == 'NLCD') 
nlcd_df_3 = pc_analysis_df %>% subset(id == '3by3') %>%
  subset(type == 'NLCD')
nlcd_df_5 = pc_analysis_df %>% subset(id == '5by5') %>%
  subset(type == 'NLCD')

nlcd_data_1 = as.data.frame(table(nlcd_df_1 %>% dplyr::select(pft_abbreviated)), stringsAsFactors = FALSE) %>% dplyr::rename(nlcd_freq = Freq, nlcd_pfts = Var1)
nlcd_data_3 = as.data.frame(table(nlcd_df_3 %>% dplyr::select(pft_abbreviated)), stringsAsFactors = FALSE) %>% dplyr::rename(nlcd_freq = Freq, nlcd_pfts = Var1)
nlcd_data_5 = as.data.frame(table(nlcd_df_5 %>% dplyr::select(pft_abbreviated)), stringsAsFactors = FALSE) %>% dplyr::rename(nlcd_freq = Freq, nlcd_pfts = Var1)
head(nlcd_data_5, 3)
```


Get all of the MODIS LC data in a format we can use to plot
```{r}
modis_lc_df_1 = pc_analysis_df %>% subset(id == '1by1') %>%
  subset(type == 'MODIS')
modis_lc_df_3 = pc_analysis_df %>% subset(id == '3by3') %>%
  subset(type == 'MODIS')
modis_lc_df_5 = pc_analysis_df %>% subset(id == '5by5') %>%
  subset(type == 'MODIS')

modis_lc_data_1 = as.data.frame(table(modis_lc_df_1$pft_abbreviated), stringsAsFactors = FALSE) %>% dplyr::rename(modis_freq = Freq, modis_pfts = Var1)
modis_lc_data_3 = as.data.frame(table(modis_lc_df_3$pft_abbreviated), stringsAsFactors = FALSE) %>% dplyr::rename(modis_freq = Freq, modis_pfts = Var1)
modis_lc_data_5 = as.data.frame(table(modis_lc_df_5$pft_abbreviated), stringsAsFactors = FALSE) %>% dplyr::rename(modis_freq = Freq, modis_pfts = Var1)
head(modis_lc_data_5, 3)
```

ROI data for Phenocams in Continental US
```{r}
# Start with sites all phenocam sites that have nlcd, modis landcover and phenocam ROI data.
roi_pfts = c()
# Loop through the phenocam sites
for (pc_site in all_sites){
  # Extract Phenocam ROI data (Plant functional data)
  pc_roi_rows = subset(roi_files, roi_files$site == pc_site)
  pc_roi_types = unique(pc_roi_rows$roitype)
  # Add all of the pc_roi_types to a char vector
  roi_pfts = c(roi_pfts, pc_roi_types)
}
roi_data = as.data.frame(table(roi_pfts), stringsAsFactors = FALSE) %>% dplyr::rename(roi_freq = Freq)
head(roi_data, 3)
```


finalize data and plot it
```{r}
nlcd_pfts     = nlcd_data_5$nlcd_pfts
modis_lc_pfts = modis_lc_data_5$modis_pfts
pc_roi_pfts   = unique(roi_data$roi_pfts)

pfts = unique(c(nlcd_pfts, modis_lc_pfts, pc_roi_pfts))

pft_df_5 = data.frame(all_pfts = pfts, stringsAsFactors = FALSE) %>% 
  dplyr::left_join(nlcd_data_5, by = c('all_pfts' = 'nlcd_pfts')) %>%
  dplyr::left_join(modis_lc_data_5, by = c('all_pfts' = 'modis_pfts')) %>%
  dplyr::left_join(roi_data, by = c('all_pfts' = 'roi_pfts'))


pc_5_p = plot_ly(x = pft_df_5$all_pfts, y = pft_df_5$roi_freq, type = 'bar', name = 'Phenocam ROI',
  marker = list(color = 'rgb(49,130,189)')) %>%
  add_trace(y = pft_df_5$nlcd_freq, name = 'NLCD LC', marker = list(color = 'rgb(256,100,100)')) %>%
  add_trace(y = pft_df_5$modis_freq, name = 'MODIS LC', marker = list(color = 'rgb(123,204,12)')) %>%
  layout(xaxis = list(title = "Plant functional types", tickangle = -45),
         yaxis = list(title = '# of Observations'),
         margin = list(b = 100),
         barmode = 'group')

pc_5_p
```






























